### ISSUE TITLE
[跨模组]钓鱼箱无法钓灾厄地形的产物

### ISSUE THREAD

**Issue by Nazgulup** [487666123/ImproveGame#101]
测试了一下，灾厄的4个新地形，只有硫磺海可以掉灾厄物品。沉沦海，硫火崖和星辉地都不行。而且好像是最近刚更新出来的问题。

**Comment by Cyrillya** [comment]
已修复 https://github.com/ForOne-Club/ImproveGame/commit/b12f3307663e6bbd0bf21ff22e042101824afaef
将随下一次更新推送到创意工坊版本
