### ISSUE TITLE
[Bug] 更好的體驗 v1.7.1.7 因 JITException 而無法載入

### ISSUE THREAD

**Issue by EvanHsieh0415** [487666123/ImproveGame#102]
- Terraria: v1.4.4.9
- tModLoader: v2024.10.3.0

![圖片](https://github.com/user-attachments/assets/e85015a1-4c34-4d06-bce3-6d2819688451)

**Comment by Cyrillya** [comment]
v1.7.1.7已经是很旧的版本了，不予以维护

**Comment by EvanHsieh0415** [comment]
> v1.7.1.7已经是很旧的版本了，不予以维护

我嘗試了各種方法，無法在 Steam 工作坊或遊戲內的模組瀏覽器下載到超過 1.7.1.7 版

**Comment by Cyrillya** [comment]
最新版本是v1.8.0.3，你的版本被锁住的最大可能是你最近玩了多人模式，而多人模式里面用的是v1.7.1.7，本地下载了模组，就不会使用创意工坊自动更新的模组了。检查一下你模组列表里更好的体验的状态，是不是“来自本地文件夹”
![image](https://github.com/user-attachments/assets/256b9e0d-77b4-4e32-9973-0b8edd850cf3)
如果是，点击“打开模组文件夹”，删除“My Games\Terraria\tModLoader\Mods”文件夹里面更好的体验的文件 `ImproveGame.tmod`
正常情况下应该显示“来源于创意工坊”
