### ISSUE TITLE
Fish caught by Fishing Machine goes straight to the inventory

### ISSUE THREAD

**Issue by cliaux** [487666123/ImproveGame#103]
Hi
I've noticed that while bait chamber is on, things started to go directly to our inventories instead of to the fishing machines.
Terraria: v1.4.4.9
tModLoader: v2024.10.3.0

![image](https://github.com/user-attachments/assets/0b9ba5a6-82d0-41d1-9e09-2bbd6a4c87ae)

**Comment by Cyrillya** [comment]
Compatibility issue with Zephyr Fish effect of Pets Overhaul Mod
Fixed https://github.com/ForOne-Club/ImproveGame/commit/f13fe53abd26811342ce71d6acd0f72b8eca1cf2
Will be published to Steam Workshop in next update
