### ISSUE TITLE
[Bug]建造魔杖错误选取方块

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#12]
物品栏中木材在前，铜矿在后，用建造魔杖放置两幢紧挨着的应该全部由木材构成，但是实际上却如下图所示，中间重叠的边框被铜矿替换。
![image](https://user-images.githubusercontent.com/50520903/203432337-7aab6aea-0390-43fd-ad80-c527b4eb22a6.png)

**Comment by 487666123** [comment]
有点怪 🧐

**Comment by Cyrillya** [comment]
经查没有在最新版本发现此问题
