### ISSUE TITLE
[崩溃]使用星爆魔杖时游戏无响应

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#18]
使用星爆魔杖时，游戏突然无响应，停在这一画面：
![崩溃前画面](https://user-images.githubusercontent.com/50520903/211471415-2557bfcd-9c19-4118-a921-d8f4e0238765.png)
随后，无法用正常方式关闭tml，最后用任务管理器关闭了tml。
[日志.zip](https://github.com/487666123/ImproveGame/files/10379325/default.zip)

**Comment by Cyrillya** [comment]
暂时没有稳定的复现方法，日志也看不出来是什么问题，先关闭了
