### ISSUE TITLE
[Bug]构造魔杖无法正确放置烟囱和武器架

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#20]
放置烟囱和武器架后，这两个家具会瞬间掉落成物品。

如果武器架里有物品，构造魔杖无法储存该物品，而是会储存一个空的武器架。

**Comment by Cyrillya** [comment]
烟囱属于原版缺陷，另外构造魔杖也不是开发重点，就不修了，如果有机会的话重置其机制再顺带修复
武器架物品不需要存，储存空武器架是预期行为

**Comment by Cyrillya** [comment]
![PixPin_2023-12-09_21-15-38](https://github.com/487666123/ImproveGame/assets/35227653/99900dd0-7626-4c26-9c87-c1df74286240)

将在下一个版本得到修复
