### ISSUE TITLE
[Bug] 无法启动mod

### ISSUE THREAD

**Issue by shulandmimi** [487666123/ImproveGame#21]
无法启动模块
![image](https://user-images.githubusercontent.com/45983040/218472377-8eae1bd5-43c4-44a6-ac89-2d42cdc78014.png)

**Comment by dfgasdfg** [comment]
不要用Preview！不要用Preview！不要用Preview！不要用Preview！不要用Preview！
在tModLoader的属性——测试版里面把版本切换为无！
所有preview版本都是仅供modder使用，玩家最好只使用无（或stable稳定）版本
