### ISSUE TITLE
[建议]关于旅行模式自动研究功能

### ISSUE THREAD

**Issue by AnTsunderecat** [487666123/ImproveGame#22]
各位开发者们，可不可以将更好的体验mod中，旅行模式自动研究功能，更改成为按住Shift+左键即可自动研究，或者不变还是标记为收藏自动研究，只是希望物品数量未达到需求也可以计算到研究里面去，就如同1.4.4.9版本的旅行模式一样，在旅行模式下，背包里面的物品数量过于多，一个研究一个研究点击非常难受，并且对于物品数量足够之后，物品不消耗这个功能，对此表示有些鸡肋了，旅行模式下物品研究成功过后，可以直接拿出一组物品，所以不再需要原来的物品，希望可以有待商榷

**Comment by Phoupraw** [comment]
可以试一试“Quick Research”这个模组，可以一键研究背包内所有物品。

**Comment by Cyrillya** [comment]
我们暂时没有添加更多旅途模式相关功能的意向
