### ISSUE TITLE
[建议]提供关闭所有效果的按钮

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#23]
提供一个关闭所有效果的按钮，让只想启用少数几个功能时不必一个一个去关闭每个功能（尤其是那些需要输入数字的）。

**Comment by Cyrillya** [comment]
直接用平衡性预设再手调就行了

**Comment by Cyrillya** [comment]
已添加 https://github.com/487666123/ImproveGame/commit/299bdeb0865592f66429fdfa03df5b89f0130143
