### ISSUE TITLE
Cross-compatibility Issue with Crash

### ISSUE THREAD

**Issue by Jar-M** [487666123/ImproveGame#28]
When installed with Abslb's Hook of Discord, making it so every tick the cursor is hovered over the piggy bank item it adds, it will attempt to open your piggy bank. In of itself not too big of an issue, however, if Magic Storage is installed and you use the # tooltip search feature, it will freeze the client until you close the game. I tried toggling all sorts of config options, but it seems none of them affect it. I also can't figure out how your mod even affects their item this way.

**Comment by Cyrillya** [comment]
Sorry for not replying in time. Does this issue still happen now?

**Comment by Cyrillya** [comment]
No furthur reply. Assume that the issue have been fixed
