### ISSUE TITLE
[建议] 大幅增加储存管理器可识别箱子的距离或者将该参数设为可由玩家更改

### ISSUE THREAD

**Issue by Anesthesia271** [487666123/ImproveGame#29]
目前版本当中，储存管理器可识别箱子的距离十分短（不到15格），这使得该物品本身想起到的功能并没有实现，我希望能够借助一个储存管理器来管理我基地当中的所有箱子，因此想知道能否增加可识别范围

**Comment by Cyrillya** [comment]
增加距离可能会引起性能问题，不过可以做成配置选项

**Comment by Anesthesia271** [comment]
期待该配置选项的早日上线

**Comment by Cyrillya** [comment]
已完成
