### ISSUE TITLE
[建议] 人物数据显示增加调整位置的选项

### ISSUE THREAD

**Issue by omymenzies** [487666123/ImproveGame#31]
希望能移动人物数据显示的位置, 让人物数据显示位于灾厄模组怒气和肾上腺素栏的右边
![image](https://github.com/487666123/ImproveGame/assets/115856305/d166f34a-511e-4f75-a5a6-7c58a00b2566)![image](https://github.com/487666123/ImproveGame/assets/115856305/acf6ddb8-17ac-4d31-a797-abb6a688ddc6)

**Comment by Cyrillya** [comment]
做的可能性不大，你可以设置成仅打开物品栏时显示（其实你可以把灾厄的怒气和肾上腺素移动一下

**Comment by Cyrillya** [comment]
下个版本(v1.6.6.2)将重置玩家属性面板，右键将可以移动属性开关按钮
