### ISSUE TITLE
[漏洞] 即使钓鱼机无法存入将要钓上的物品，也会播放动画

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#38]
当钓鱼机的所有格子都装有物品时，只有可以堆叠到现有物品上的物品才可以被成功钓起，但是即使不能堆叠到现有物品上（即不能成功钓起），也会播放从物品水的位置飞入钓鱼机的动画。

**Comment by Cyrillya** [comment]
将在下一个版本修复

**Comment by Phoupraw** [comment]
似乎并未修复。
![image](https://github.com/487666123/ImproveGame/assets/50520903/390faf72-1d9d-49c9-b9e0-a7b239de3db4)

**Comment by Cyrillya** [comment]
你是用1.4.4分支的最新提交测试的吗？这个修复还没有更新到创意工坊版本

**Comment by Phoupraw** [comment]
> 你是用1.4.4分支的最新提交测试的吗？这个修复还没有更新到创意工坊版本

哦，我是直接从创意工坊下载的，我看到群里发了更新日志，以为创意工坊的就是最新版的。
