### ISSUE TITLE
[漏洞] 旗帜盒/药水袋右键错误

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#40]
右键旗帜盒，会把旗帜盒拿起在鼠标上，同时打开旗帜盒界面，该界面不属于鼠标上的旗帜盒，对该界面做的任何修改、放入的任何物品，都不会影响到鼠标上的旗帜盒，在关闭该界面后，里面的物品随之消失。

药水袋同理。

**Comment by Cyrillya** [comment]
已修复 https://github.com/487666123/ImproveGame/commit/a1a91df1830f5a0e9bd261b958d059924c264ded
