### ISSUE TITLE
Strange issue with a Thorium armor set - Terrarium armor

### ISSUE THREAD

**Issue by GregariousJB** [487666123/ImproveGame#41]
https://github.com/487666123/ImproveGame/assets/540857/300f065a-456c-45a4-b304-aa5a0353c2ca

Terraria 1.4.4.9
Thorium 1.7.1.2
Quality of Life 1.6.5.4

Very strange bug - the set bonus of Thorium's Terrarium armor seems to swap repeatedly between set bonus focuses.

https://thoriummod.wiki.gg/wiki/Terrarium_armor

"Its set bonus grants a "focus" based on which class the player has the most (additive and multiplicative) bonus damage in". 

The bug stops when Quality of Life is disabled.

Thank you.

**Comment by Cyrillya** [comment]
Pretty strange. Can you send me your player file?

**Comment by GregariousJB** [comment]
> Pretty strange. Can you send me your player file?

There's been an update to Thorium mod and tModloader since I made this issue, and I can't seem to duplicate it anymore. I suppose it's fixed. Thank you anyway.
