### ISSUE TITLE
[漏洞]多人模式（服务器）下空间魔杖放置平台bug

### ISSUE THREAD

**Issue by ckbso19** [487666123/ImproveGame#44]
多人模式下使用空间模式放置平台，有概率导致平台错位，具体表现为我在修世界平台，另一位玩家在修地狱平台，我这边无故出现他那边的平台，他那边也会无故出现我的平台

**Comment by Cyrillya** [comment]
请问你的更好的体验版本是？这个Bug应该在v1.6.5.1的时候就已经修复了

**Comment by Cyrillya** [comment]
无后续回复，默认为问题已解决
