### ISSUE TITLE
[漏洞] 构造魔杖无法放置火把

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#45]
![更好的体验构造魔杖无法放置火把 mp4_20231018_052927 771](https://github.com/487666123/ImproveGame/assets/50520903/60bdae22-b7c0-4ed9-9b03-420726aae986)
![更好的体验构造魔杖无法放置火把 mp4_20231018_052932 175](https://github.com/487666123/ImproveGame/assets/50520903/cc9b9ccb-a453-4811-84bf-4808742c9398)
视频发在群里。

**Comment by Cyrillya** [comment]
将在下一个版本得到修复
