### ISSUE TITLE
[BUG] [v1.6.6] 部分物品在合成表里同级锭不能互相替代使用的问题

### ISSUE THREAD

**Issue by nullpo21** [487666123/ImproveGame#48]
上一个版本里，一系列魔杖在合成时，部分锭是可以**平级替代**的，比如金锭/铂金锭，猩红锭/魔矿锭，秘银锭/山铜锭；更新之后，部分物品的锭变成了指定的锭，而不是锭group。

现在发现存在该问题的物品有：
- 构造魔杖，秘银锭
- 建造魔杖，金锭
- 勘探无人机，金锭
- 液体魔杖，金锭
- 自动钓鱼机，铜锭
- 储存管理器，金锭
- 空间魔杖，魔矿锭

**Comment by Cyrillya** [comment]
这应该是一个mod冲突，甚至可能与tmodloader本身有关，因为我这边并没有出现这样的bug，相关的代码也从来没有更改过
请附上你开启的mod列表

**Comment by Cyrillya** [comment]
已修复 https://github.com/487666123/ImproveGame/commit/ec4bd1f8d391093ebc6c621b61ce9d8a0413fd1d
