### ISSUE TITLE
[建议][跨模组] 兼容《Block的更好信息饰品》

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#49]
使[《Block的更好信息饰品》](https://steamcommunity.com/sharedfiles/filedetails/?id=3026604494)的信息饰品像原版信息饰品一样也能在存钱罐、保险箱、护卫熔炉、大背包中生效。

**Comment by Cyrillya** [comment]
已解决 https://github.com/487666123/ImproveGame/commit/cc4028c05bc63d78a7a9933acbc95db7c807cec5
