### ISSUE TITLE
[建议] 提高稻草人的默认生命值

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#50]
游戏后期有很多武器一次就能造成超过2000伤害，直接把稻草人秒了，每次都要手动`/dummy lifemax 12345679`比较麻烦。

**Comment by Cyrillya** [comment]
计划进行一个假人重做，到时会进行优化的

**Comment by Cyrillya** [comment]
虽然没有假人重做，但是提升了默认生命值
