### ISSUE TITLE
[漏洞] 提高工具使用速度对钢丝钳不生效

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#51]
宏伟蓝图没有只能光标，因此清理一些非平直线路时远不如支持智能光标的钢丝钳好用，但是钢丝钳使用速度并不受“提高工具使用速度”影响，导致用起来比较慢。

**Comment by Cyrillya** [comment]
已修复 https://github.com/487666123/ImproveGame/commit/e0f6122afe46d2901359a700600645544899e18b
