### ISSUE TITLE
[建议] 液体魔杖增加功能：直接吸收所有种类液体

### ISSUE THREAD

**Issue by 3CB3EC** [487666123/ImproveGame#54]
目前原版已经有配方将三种海绵合成为可以吸收所有种类液体的超级吸收绵，建议可以将类似功能增加到液体魔杖，以省去拥有超级吸收棉后，还是要手动切换液体魔杖吸收液体类型的这一步骤

**Comment by Cyrillya** [comment]
已添加 https://github.com/ForOne-Club/ImproveGame/commit/535cea81f7f5b8bb07cfd9e164d461b14c2d71f8
将在下个版本推出
