### ISSUE TITLE
[漏洞][跨模组] 《附魔月亮》的着色器不正常生效

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#62]
[《附魔月亮》(Enchanted Moons)](https://steamcommunity.com/sharedfiles/filedetails/?id=3030483105)在附魔月亮升起时会让屏幕变成对应的颜色，类似血月，但是《更好的体验》似乎覆写了光照机制，即使没有启用“光照无视物块”，附魔月亮的着色器也未生效。
这是没有安装《更好的体验》时的樱花月亮（游戏内截图）：
![Capture 2024-01-09 01_20_32](https://github.com/487666123/ImproveGame/assets/50520903/44c07607-b33a-49f2-966d-b3c11dee0050)
这是安装了《更好的体验》时的樱花月亮（游戏内截图看起来着色器是正常的，但是用外部工具截图就能看出来着色器未生效，此处为QQ截图）：
![image](https://github.com/487666123/ImproveGame/assets/50520903/d34fc20d-2672-45d5-a7bd-bc4aa5c846b9)
当暂停时，着色器正常生效（QQ截图）：
![image](https://github.com/487666123/ImproveGame/assets/50520903/65e0c02f-9f86-41c1-b4b9-26cb262c2e04)

**Comment by Cyrillya** [comment]
可能和 #72 是同一个问题，已在最新版本修复。若Bug还是出现再打开此issue
