### ISSUE TITLE
[漏洞] 开关大地图重置数项设定

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#63]
打开大地图、关闭大地图会重置数项设定。
## 已发现的重置项
- 药水袋和旗帜盒的窗口位置变回屏幕中央
- 无限增益站组合刷怪倍率变回1
## 药水袋和旗帜盒窗口位置重置
药水袋和旗帜盒的窗口的默认位置是在屏幕中央：
![image](https://github.com/487666123/ImproveGame/assets/50520903/d51f5483-6d3e-4a3b-add1-8883a1c2eab6)
将其拖拽至其它地方：
![image](https://github.com/487666123/ImproveGame/assets/50520903/af4f368a-f943-49f1-95d0-d8cdd3253cad)
打开大地图，关闭大地图，然后再打开药水袋，发现窗口位置重置。

**Comment by Cyrillya** [comment]
已修复 https://github.com/487666123/ImproveGame/commit/1ecb37e5e2ff30b269cb4a6476471f1929e79930
