### ISSUE TITLE
[漏洞] 无限增益站暗影蜡烛无实际效果

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#65]
如题。

版本：v1.6.7.0

**Comment by Cyrillya** [comment]
我这边测出来是有实际效果的，在城镇里开10x刷怪，打开无限增益的影烛之后，BGM会用大概8s时间变成普通地表bgm，然后开始生成一大堆史莱姆。要不你再试试？我先关了这个issue

**Comment by Phoupraw** [comment]
我的一个世界里影烛没用，把世界复制了一遍也没用，另外两个世界影烛有用。我在群里发了那个影烛没用的世界，你试试你那边有没有用？。
