### ISSUE TITLE
[漏洞] 空间魔杖能够在镐力不足110%时替换下方沙块

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#66]
> 沙块和其他受重力影响的物块只能在使用至少具有 110% 镐力的镐或钻头（如钴镐）时被物块交换。在使用较弱的镐时，只有一列沙块的最上方一个能够被物块交换为不会下落的物块。所有镐和钻头都可以将沙块和其他受重力影响的物块进行物块交换。
>
> ——[Wiki](https://terraria.wiki.gg/zh/wiki/%E6%B2%99%E5%9D%97#%E5%A4%87%E6%B3%A8)

但是空间魔杖能够在镐力不足110%时用不可下落方块替换上面有可下落方块的可下落方块。

**Comment by Cyrillya** [comment]
我个人认为这是个较好的特性
