### ISSUE TITLE
[漏洞] 影烛增益站不正确移除

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#67]
身上没有影烛时，增益列表里仍有影烛。
（可能与 #65 有关。这个世界里，影烛增益站不生效。）
![image](https://github.com/487666123/ImproveGame/assets/50520903/572f9929-5ede-44f0-8340-10f62388c983)

**Comment by Cyrillya** [comment]
已修复 https://github.com/487666123/ImproveGame/commit/824b81de377ff69cceaface0be2d3745988c2a4a
