### ISSUE TITLE
Null reference exception in DumpIL

### ISSUE THREAD

**Issue by Chicken-Bones** [487666123/ImproveGame#68]
at https://github.com/487666123/ImproveGame/blob/1.4.4/Content/Patches/MinorPatches.cs#L827

```cs
MonoModHooks.DumpIL(ImproveGame.Instance, il);
```

`ImproveGame.Instance` is `null` at the time the IL hook is loaded.

`Mod.Load` is called after `Mod.Autoload`
You should set `ImproveGame.Instance` in your mod's constructor, like this:
```cs
ImproveGame() {
    Instance = this;
}
```

alternatively, use `ModContent.GetInstance<ImproveGame>()`

**Comment by Cyrillya** [comment]
Fixed in https://github.com/487666123/ImproveGame/commit/8a00906bd500ba1de0edacee27a667b76533d32d
Use `ModContent.GetInstance<ImproveGame>()` now
