### ISSUE TITLE
灾厄重新召唤卡兰德的魔镜会重复召唤第一把不会召唤不同的神兵

### ISSUE THREAD

**Issue by caidecongtou** [487666123/ImproveGame#73]
正常召唤
![20240318212118_1](https://github.com/487666123/ImproveGame/assets/90243830/ca00a57f-f7a2-44f1-a6f2-559e5ae29e85)
死亡后重新召唤
![20240318212152_1](https://github.com/487666123/ImproveGame/assets/90243830/992881f8-eab5-4874-bb91-f1801a28d668)

**Comment by Cyrillya** [comment]
已修复，请等待创意工坊版本更新 https://github.com/487666123/ImproveGame/commit/4219eda85a6610ea5c449d7517e09f44b0c286f3
