### ISSUE TITLE
Home-teleporting item upgrade not working

### ISSUE THREAD

**Issue by aacknov** [487666123/ImproveGame#77]
I'm playing the Thorium mod and it has a direct upgrade for the shellphone. back when I had the shellphone, the keybind I set for automatically using it to take me home was working perfectly fine, even when it was on the beach or underworld mode, but ever since the upgrade it seems like the mod doesn't detect it as a "home teleporting item". It'd be great if you could introduce it as such item, or even make it configurable so we can give it the item id and it'd detect it as such. Also thanks for a wonderful job on this mod

**Comment by Cyrillya** [comment]
We will add cross-mod support for it as a home teleporting item

**Comment by Cyrillya** [comment]
Fixed https://github.com/487666123/ImproveGame/commit/6c48453432364021727e95b5704ec1be49867b07
Please wait for the update to steam workshop
