### ISSUE TITLE
【特性】把手动分类版的储存管理器加回来

### ISSUE THREAD

**Issue by CgAu3** [487666123/ImproveGame#78]
给自己不整理箱子的人理发≠不给自己整理箱子的人理发。
不能自己手动分类，对于对分类有自己的理解的、或者有强迫症的玩家很可能是难以接受的。对于二者皆有的我，就会变成不如直接用箱子；当然，我也几乎从来不用魔法存储。
建议加入选项，开启后可以自己手动管理储存管理器的分类；
或者单独再加一个手动分类版的储存管理器物品。
就这样。

**Comment by Cyrillya** [comment]
众口难调。根据手动分类期间得到的反馈，大部分玩家更倾向自动分类
加回来不现实，因为要改动的东西太多，代码管理有困难
