### ISSUE TITLE
[建议] [跨模组] 自动收纳《瑟银》征服者勋章

### ISSUE THREAD

**Issue by Phoupraw** [487666123/ImproveGame#86]
征服者勋章是与赏金猎人交易用的货币，希望可以像护卫奖章一样自动收纳进钱币槽。

**Comment by hezuo1hao** [comment]
加了 https://github.com/ForOne-Club/ImproveGame/commit/5828c68bb8b8390323ec1b0b472a6ec0ec9ae17e
