### ISSUE TITLE
[bug]在灾法环境下，多人模式进入世界钓鱼机无法钓鱼

### ISSUE THREAD

**Issue by uzu11** [487666123/ImproveGame#95]
使用mod：灾厄+灾厄汉化，法狗魂石+法狗突变+汉化+法狗dlc，hero，更好的体验
附世界存档：
[Worlds.zip](https://github.com/user-attachments/files/17649216/Worlds.zip)

**Comment by hezuo1hao** [comment]
哥们你.twld文件去哪里了？

**Comment by uzu11** [comment]
不好意思传的时候少选了一个，重新上传了
[Worlds.zip](https://github.com/user-attachments/files/17686205/Worlds.zip)
其实新开一个世界进多人模式复现也是很容易的，仅当开DLC的时候会钓不上鱼

**Comment by hezuo1hao** [comment]
@Cyrillya 鏖战三个小时败于其手，可以复现
开启[Calamity - Fargo's Souls DLC mod](https://steamcommunity.com/sharedfiles/filedetails/?id=3044249615)，并在多人模式下，钓鱼机无法正常工作

**Comment by Cyrillya** [comment]
已修复 https://github.com/ForOne-Club/ImproveGame/commit/981987d982d31a75ca94d10013acc26d7e9bb5c7
将在下个版本更新

**Comment by Cyrillya** [comment]
修复后又出现了无法识别部分环境的问题，等待进一步修复
