### ISSUE TITLE
[建议]增加召唤师重召唤配置菜单

### ISSUE THREAD

**Issue by Titer104343** [487666123/ImproveGame#99]
召唤师死亡后重召唤后只能全部召唤最后一个选中的召唤物
有些召唤物需要混搭才可以使伤害最大化
有些模组 如灾厄中有单独只能召唤一个的召唤物 重新召唤过于麻烦
可以添加一个召唤师重召唤的配置菜单 可以自由配置重召唤后召唤物的种类及数量

**Comment by Cyrillya** [comment]
考虑到更好的体验是一个集成式的模组，不打算进一步改进重召唤功能，因为加入这些功能可能会导致和部分模组起冲突，难以维护
请用Summoner's Association模组，这个已经在该功能的简介中说明了
![image](https://github.com/user-attachments/assets/7bc5248c-efc8-44bd-8ad3-33c255711858)
